server:
  port: 4123
  name: 'My Minecraft Server'
  password: 'NULL'
  tickrate: 20
storage:
  type: 'JSON'
  host: 'NULL'
  user: 'NULL'
  password: 'NULL'
anonymous:
  allow: true
  permissions:
  - livekit.module.map
  - livekit.module.players
  - livekit.players.other
permissions:
  useVault: false
  default:
  - livekit.commands.basic
  - livekit.module.map
  - livekit.module.players
  - livekit.module.weathertime
  - livekit.module.chat
  - livekit.module.poi
  - livekit.chat.write
  - livekit.poi.personalpins
  - livekit.players.other
modules:
  LiveMapModule:
    enabled: true
  PlayerModule:
    enabled: true
  WeatherTimeModule:
    enabled: true
  AdminModule:
    enabled: true
  ChatModule:
    enabled: true
  POIModule:
    enabled: true
    personalpins: 5
    teleport_spawn: false
    teleport_bed: false
  ConsoleModule:
    enabled: true
    password: change_me
  InventoryModule:
    enabled: true
