server.port: 4123
server.name: 'My Minecraft Server'
server.tickrate: 20
#password protect access to LiveKit
server.password: null

#allow app clients to view livemap/online players without claiming an account
anonymous:
  allow: true
  permissions:
    - livekit.module.map
    - livekit.module.players

#wether to use permissions (Vault) or if use==false, use default permissions for every player
permissions:
  use: false
  default:
    - livekit.commands.basic
    - livekit.module.map
    - livekit.module.players
    - livekit.module.weathertime
    - livekit.module.chat

#which modules to enable
modules:
  LiveMapModule:
    enabled: true
    worlds:
      - world
      - world_nether
      - world_the_end
    cpuTime: 20
  PlayerModule:
    enabled: true
  WeatherTimeModule:
    enabled: true
  AdminModule:
    enabled: true
  ChatModule:
    enabled: true
