server:
  port: 4123
  name: My Minecraft Server
  password: null
  tickrate: 20
anonymous:
  allow: true
  permissions:
  - livekit.module.map
  - livekit.module.players
permissions:
  useVault: false
  default:
  - livekit.commands.basic
  - livekit.module.map
  - livekit.module.players
  - livekit.module.weathertime
  - livekit.modules.chat
  - livekit.chat.write
modules:
  LiveMapModule:
    enabled: true
  PlayerModule:
    enabled: true
  WeatherTimeModule:
    enabled: true
  AdminModule:
    enabled: true
  ChatModule:
    enabled: true
