server.port: 8123
server.name: 'My Minecraft Server'
server.tickrate: 8

#allow app clients to view livemap/online players without claiming an account
anonymous:
  allow: true
  permissions:
    - livekit.basics.map
    - livekit.basics.players

#wether to use permissions (Vault) or if use==false, use default permissions for every player
permissions:
  use: true
  default:
    - livekit.basics.claim
    - livekit.basics.map
    - livekit.basics.players
    - livekit.basics.weathertime

#which modules to enable
modules:
  LiveMapModule:
    enabled: true
    world: 'world'
  PlayerModule:
    enabled: true
