server:
  port: 4123
  name: 'My Minecraft Server'
  password: 'NULL'
  searchDiscoverable: true
  tickrate: 20
storage:
  type: 'SQLITE'
  sql:
    host: 'NULL'
    database: 'NULL'
    user: 'NULL'
    password: 'NULL'
anonymous:
  allow: true
  permissions:
  - livekit.module.chat
  - livekit.module.map
  - livekit.module.players
  - livekit.players.other
permissions:
  useVault: false
  default:
  - livekit.commands.basic
  - livekit.module.map
  - livekit.module.players
  - livekit.module.weathertime
  - livekit.module.chat
  - livekit.module.poi
  - livekit.module.statistics
  - livekit.chat.write
  - livekit.poi.personalpins
  - livekit.players.other
modules:
  LiveMapModule:
    enabled: true
  PlayerModule:
    enabled: true
  WeatherTimeModule:
    enabled: true
  AdminModule:
    enabled: true
  ChatModule:
    enabled: true
    offlineFormat: '&7[Offline]&r <{prefix}&r{name}&r{suffix}&r> {message}'
  POIModule:
    enabled: true
    personalpins: 5
    teleport_spawn: false
    teleport_bed: false
  ConsoleModule:
    enabled: true
    password: change_me
  InventoryModule:
    enabled: true
  StatisticsModule:
    enabled: true
  PerformanceModule:
    enabled: true
plugins:
  DiscordSRV:
    enabled: false
    channelIDs:
    - all