main: at.livekit.plugin.Plugin
name: LiveKit
version: 1.4.0
author: livekitapp@gmail.com
description: Connector plugin for LiveKit. Allows LiveKit App to connect to server
api-version: 1.16
softdepend: [Vault]
commands:
  livekit:
    description: LiveKit commands
    usage: /livekit
libraries:
    - org.xerial:sqlite-jdbc:jar:3.34.0
    - mysql:mysql-connector-java:jar:8.0.25
    - org.postgresql:postgresql:jar:42.2.21