main: at.livekit.plugin.Plugin
name: LiveKit
version: 1.5.0-R0.2-ALPHA
author: livekitapp@gmail.com
description: Connector plugin for LiveKit. Allows LiveKit App to connect to server
api-version: 1.16
softdepend: [Vault,DiscordSRV]
commands:
  livekit:
    description: LiveKit commands
    usage: /livekit