api-version: 1.16
main: at.livekit.plugin.Plugin
name: LiveKit
version: 1.4.6-BETA-0.1
author: livekitapp@gmail.com
description: Connector plugin for LiveKit. Allows LiveKit App to connect to server
softdepend: [Vault,DiscordSRV]
commands:
  livekit:
    description: LiveKit commands
    usage: /livekit