main: at.livekit.plugin.Plugin
name: LiveKit
version: 0.1
author: Philip
description: Server connector for something epic
api-version: 1.16
softdepend: [Vault]
commands:
  livekit:
    description: LiveKit command
    usage: /livekit
    permission: livekit.basics
    permission-message: You don't have the livekit.basics permission.