main: at.livekit.plugin.Plugin
name: LiveKit
version: 0.1.0
author: livekitapp@gmail.com
description: Connector plugin for LiveKit. Allows LiveKit App to connect to server
api-version: 1.16
softdepend: [Vault]
commands:
  livekit:
    description: LiveKit commands
    usage: /livekit